version: '3.8'

services:
  database:
    container_name: backend-db-container
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: smdb
      MYSQL_USER: smuser
      MYSQL_PASSWORD: smuser
    ports:
      - '33060:3306'
    volumes:
      - ./backend/docker/mysql:/var/lib/mysql

  php:
    container_name: backend-php-container
    build:
      context: ./backend/docker/php
    ports:
      - '9000:9000'
    volumes:
      - ./backend:/var/www/symfony
    depends_on:
      - database

  nginx:
    container_name: backend-nginx-container
    image: nginx:stable-alpine
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/symfony
      - ./backend/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  vue:
    container_name: frontend-vue-container
    build:
      context: ./frontend
    ports:
      - '3000:8080'
    volumes:
      - ./frontend:/frontend
